// <auto-generated />
using System;
using CadernoDigitalColaborativo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadernoDigitalColaborativo.Migrations
{
    [DbContext(typeof(CadernoDigitalColaborativoContext))]
    [Migration("20200923224533_mudanca_post")]
    partial class mudanca_post
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText");

                    b.Property<DateTime>("CommentTime");

                    b.Property<int>("IdUsuario");

                    b.Property<int?>("PostId");

                    b.Property<int?>("UsuarioId");

                    b.Property<int?>("UsuarioPostId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioPostId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.DislikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DislikedAt");

                    b.Property<int>("IdUsuario1");

                    b.Property<int>("IdUsuario2");

                    b.Property<int?>("Usario1Id");

                    b.Property<int?>("Usario2Id");

                    b.HasKey("Id");

                    b.HasIndex("Usario1Id");

                    b.HasIndex("Usario2Id");

                    b.ToTable("Dislike");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.LikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUsuario1");

                    b.Property<int>("IdUsuario2");

                    b.Property<int?>("PostModelId");

                    b.Property<int?>("Usario1Id");

                    b.Property<int?>("Usario2Id");

                    b.HasKey("Id");

                    b.HasIndex("PostModelId");

                    b.HasIndex("Usario1Id");

                    b.HasIndex("Usario2Id");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.PostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FotoUsuario");

                    b.Property<int>("IdUsuario");

                    b.Property<string>("Imagem");

                    b.Property<string>("NomeUsuario");

                    b.Property<DateTime>("PostTime");

                    b.Property<string>("TextoPost");

                    b.Property<int?>("UsuarioPostId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioPostId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoIngresso");

                    b.Property<string>("Curso");

                    b.Property<int>("CursoId");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("ProfilePictureUrl");

                    b.Property<int>("Semestre");

                    b.Property<string>("Senha");

                    b.Property<int>("Situacao");

                    b.Property<string>("Sobrenome");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.CommentModel", b =>
                {
                    b.HasOne("CadernoDigitalColaborativo.Models.PostModel", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "UsuarioPost")
                        .WithMany()
                        .HasForeignKey("UsuarioPostId");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.DislikeModel", b =>
                {
                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "Usario1")
                        .WithMany()
                        .HasForeignKey("Usario1Id");

                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "Usario2")
                        .WithMany()
                        .HasForeignKey("Usario2Id");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.LikeModel", b =>
                {
                    b.HasOne("CadernoDigitalColaborativo.Models.PostModel")
                        .WithMany("Likes")
                        .HasForeignKey("PostModelId");

                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "Usario1")
                        .WithMany()
                        .HasForeignKey("Usario1Id");

                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "Usario2")
                        .WithMany()
                        .HasForeignKey("Usario2Id");
                });

            modelBuilder.Entity("CadernoDigitalColaborativo.Models.PostModel", b =>
                {
                    b.HasOne("CadernoDigitalColaborativo.Models.Usuario", "UsuarioPost")
                        .WithMany()
                        .HasForeignKey("UsuarioPostId");
                });
#pragma warning restore 612, 618
        }
    }
}
